gdcl/urls.py
from django.conf.urls import url
from . import views

app_name = 'gdcl'
urlpatterns = [
    # 首页
    url(r'^$', views.index, name='index'),

    # 企业概况五个
    url(r'^description/$', views.description, name='description'),
    url(r'^boss/$', views.boss, name='boss'),
    url(r'^organization/$', views.organization, name='organization'),
    url(r'^certification/$', views.certification, name='certification'),
    url(r'^reputation/$', views.reputation, name='reputation'),

    # 企业文化五个
    url(r'^logo/$', views.logo, name='logo'),
    url(r'^management/$', views.management, name='management'),
    url(r'^show/$', views.show, name='show'),
    url(r'^video/$', views.video, name='video'),
    url(r'^employee/$', views.employee, name='employee'),

    # 工程业绩三个
    url(r'^rewards/$', views.rewards, name='rewards'),
    url(r'^project_show/$', views.project_show, name='project_show'),
    url(r'^project_photo/$', views.project_photo, name='project_photo'),

    # 新闻资讯四个
    url(r'^company_news/$', views.company_news, name='company_news'),
    url(r'^movement/$', views.movement, name='movement'),
    url(r'^note/$', views.note, name='note'),
    url(r'^others/$', views.others, name='others'),

    # 关于我们两个
    url(r'^recruitment/$', views.recruitment, name='recruitment'),
    url(r'^contact/$', views.contact, name='contact'),

    # 项目实拍
    url(r'^yqsz/$', views.yqsz, name='yqsz'),
    url(r'^ylgc/$', views.ylgc, name='ylgc'),
    url(r'^zhgxhmt/$', views.zhgxhmt, name='zhgxhmt'),
    url(r'^zhsdjzxjxl/$', views.zhsdjzxjxl, name='zhsdjzxjxl'),
    url(r'^bthxx/$', views.bthxx, name='bthxx'),
]

gdcl_new/urls.py
from django.contrib import admin
from django.urls import path,include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('gdcl.urls')),
]

gdcl/models.py
from django.db import models

# Create your models here.

gdcl/views.py
from django.shortcuts import render

# Create your views here.

# 首页
def index(request):
    return render(request, 'index.html')

# 企业概况
# 企业简介
def description(request):
    return render(request, 'description.html')
# 董事长致辞
def boss(request):
    return render(request, 'boss.html')
# 组织架构
def organization(request):
    return render(request, 'organization.html')
# 公司资质
def certification(request):
    return render(request, 'certification.html')
# 公司荣誉
def reputation(request):
    return render(request, 'reputation.html')

# 企业文化
# 品牌标志
def logo(request):
    return render(request, 'logo.html')
# 管理理念
def management(request):
    return render(request, 'management.html')
# 形象展示
def show(request):
    return render(request, 'show.html')
# 企业视频
def video(request):
    return render(request, 'video.html')
# 员工风采
def employee(request):
    return render(request, 'employee.html')

# 工程业绩
# 获奖工程
def rewards(request):
    return render(request, 'rewards.html')
# 项目展示
def project_show(request):
    return render(request, 'project_show.html')
# 项目实拍
def project_photo(request):
    return render(request, 'project_photo.html')

# 新闻资讯
# 企业新闻
def company_news(request):
    return render(request, 'company_news.html')
# 行业动态
def movement(request):
    return render(request, 'movement.html')
# 通知公告
def note(request):
    return render(request, 'note.html')
# 其他资讯
def others(request):
    return render(request, 'others.html')

# 加入我们
# 人才招聘
def recruitment(request):
    return render(request, 'recruitment.html')
# 联系我们
def contact(request):
    return render(request, 'contact.html')

#银泉山庄
def yqsz(request):
    return  render(request,'yqsz.html')

#鱼林广场
def ylgc(request):
    return render(request,'ylgc.html')

#珠海港鑫和码头
def zhgxhmt(request):
    return render(request,'zhgxhmt.html')

#珠海市第九中学教学楼
def zhsdjzxjxl(request):
    return render(request,'zhsdjzxjxl.html')

#白藤湖小学
def bthxx(request):
    return render(request,'bthxx.html')

templates/employee.html
{% load staticfiles %}
<input type='hidden' id='loginusername' value='暂无'><input type='hidden' id='loginemail'
                                                          value='暂无'><!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">

    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>企业文化-广东成利建设集团有限公司</title>
    <link rel="stylesheet" href="{% static 'css/default.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/idangerous_swiper.css' %}">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/SuperSlide.js' %}"></script>
    <script src="{% static 'js/idangerous.swiper.min.js' %}"></script>
    <script src="{% static 'js/idangerous.swiper.progress.js' %}"></script>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="//cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="//cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<div id="index-box">
    <div id="head">
        <img src="{% static 'images/logo.png' %}">
        <div class="head-search">
            <form action="" method="post">
                {% csrf_token %}
                <input type="text" name="keyword">
                <input type="submit" class="submit" value="搜索">
            </form>
        </div>
    </div>
</div>
<!--menu start-->
<div id="menu">
    <div class="menu-top">
        <ul>
            <li>
                <a href={% url 'gdcl:index' %}>首页</a></li>
            <li>
                <a href={% url 'gdcl:description' %}>企业概况</a></li>
            <li class="select">
                <a href={% url 'gdcl:logo' %}>企业文化</a></li>
            <li>
                <a href={% url 'gdcl:rewards' %}>工程业绩</a></li>
            <li>
                <a href={% url 'gdcl:company_news' %}>新闻资讯</a></li>
            <li>
                <a href={% url 'gdcl:contact' %}>加入我们</a></li>
        </ul>
    </div>
    <!--中间部分-->
    <div class="banner-min"
         style="background:url({% static 'images/20170301111230_24232.jpg' %}) no-repeat top center;"></div>
    <div id="banner-middle">
        <div class="qygk-left">
            <div class="qygk-left-top">
                <b></b>
                <h3>企业文化</h3>
            </div>
            <div class="qygk-left-bottom">
                <ul>
                   <li><i class="iconfont newsfont">></i>
                        <a href={% url 'gdcl:logo' %}>品牌标志</a></li>
                    <li><i class="iconfont newsfont">></i>
                        <a href={% url 'gdcl:management' %}>管理理念</a></li>
                    <li><i class="iconfont newsfont">></i>
                        <a href={% url 'gdcl:show' %}>形象展示</a></li>
                    <li><i class="iconfont newsfont">></i>
                        <a href={% url 'gdcl:video' %}>企业视频</a></li>
                    <li><i class="iconfont newsfont">></i>
                        <a href={% url 'gdcl:employee' %} class="menu-on">员工风采</a></li>
                </ul>
            </div>
        </div>
        <div class="qygk-right">
            <div class="munu-info">
                <div id="location">
                    <b></b><span>当前位置 -> <a href={% url 'gdcl:index' %}>首页</a>-><a href={% url 'gdcl:logo' %}>企业文化</a>-><a
                        href={% url 'gdcl:employee' %}>员工风采</a></span>
                </div>
                <div class="menu-content">
                    <div class="hjgc">
                        <ul id="layer-photos">
                            <li>
                                <a href="javascript:;">
                                    <div><img src="/upload/attached/image/20170505/20170505113634_32258.jpg"
                                              class="showImgs" alt="三八节女职工长隆一日游"></div>
                                    <p>三八节女职工长隆一日游</p>
                                </a>
                            </li>
                            <li>
                                <a href="javascript:;">
                                    <div><img src="/upload/attached/image/20170505/20170505113538_47071.jpg"
                                              class="showImgs" alt="谢景清同志被评为2014年度珠海市道德模范员工"></div>
                                    <p>谢景清同志被评为2014年度珠海市道德模范员工</p>
                                </a>
                            </li>
                            <li>
                                <a href="javascript:;">
                                    <div><img src="/upload/attached/image/20170505/20170505113449_13021.jpg"
                                              class="showImgs" alt="董事长代表公司发言"></div>
                                    <p>董事长代表公司发言</p>
                                </a>
                            </li>
                            <li>
                                <a href="javascript:;">
                                    <div><img src="/upload/attached/image/20170505/20170505113415_56701.jpg"
                                              class="showImgs" alt="公司被评为2014年度珠海市文明企业"></div>
                                    <p>公司被评为2014年度珠海市文明企业</p>
                                </a>
                            </li>
                            <li>
                                <a href="javascript:;">
                                    <div><img src="/upload/attached/image/20170505/20170505113316_76978.jpg"
                                              class="showImgs" alt="公司荣获2014年年度全国企业文化建设先进单位"></div>
                                    <p>公司荣获2014年年度全国企业文化建设先进单位</p>
                                </a>
                            </li>
                            <li>
                                <a href="javascript:;">
                                    <div><img src="/upload/attached/image/20170505/20170505113201_49770.jpg"
                                              class="showImgs" alt="大会掠影"></div>
                                    <p>大会掠影</p>
                                </a>
                            </li>
                            <li>
                                <a href="javascript:;">
                                    <div><img src="/upload/attached/image/20170505/20170505113111_14876.jpg"
                                              class="showImgs" alt="大会掠影2"></div>
                                    <p>大会掠影2</p>
                                </a>
                            </li>
                            <li>
                                <a href="javascript:;">
                                    <div><img src="/upload/attached/image/20170505/20170505113028_52540.jpg"
                                              class="showImgs" alt="东澳岛植树（一）"></div>
                                    <p>东澳岛植树（一）</p>
                                </a>
                            </li>
                            <li>
                                <a href="javascript:;">
                                    <div><img src="/upload/attached/image/20170505/20170505112947_37057.jpg"
                                              class="showImgs" alt="东澳岛植树（二）"></div>
                                    <p>东澳岛植树（二）</p>
                                </a>
                            </li>
                            <li>
                                <a href="javascript:;">
                                    <div><img src="/upload/attached/image/20170505/20170505112803_96761.jpg"
                                              class="showImgs" alt="东澳岛植树（三）"></div>
                                    <p>东澳岛植树（三）</p>
                                </a>
                            </li>
                            <li>
                                <a href="javascript:;">
                                    <div><img src="/upload/attached/image/20170505/20170505112705_82936.jpg"
                                              class="showImgs" alt="农场烧烤"></div>
                                    <p>农场烧烤</p>
                                </a>
                            </li>
                            <li>
                                <a href="javascript:;">
                                    <div><img src="/upload/attached/image/20170505/20170505112404_82862.jpg"
                                              class="showImgs" alt="农场烧烤"></div>
                                    <p>农场烧烤</p>
                                </a>
                            </li>
                        </ul>
                    </div>
                </div>
            </div>
        </div>
        <script src="/template/default/js/layer.js"></script>
        <script>
            layer.photos({
                photos: '#layer-photos',
                closeBtn: 1,
            });
        </script>

    </div>
    <!--footer-->
<div style="clear:both;"></div>
<div id="footer">
    <div class="foot-top">
        <ul>
            <li><a href={% url 'gdcl:index' %}>首页</a></li>
            <li><a href={% url 'gdcl:description' %}>企业概况</a></li>
            <li><a href={% url 'gdcl:rewards' %}>工程业绩</a></li>
            <li><a href={% url 'gdcl:contact' %}>加入我们</a></li>
        </ul>
    </div>
    <p>地址：珠海市香洲区九州大道中1009号钰海环球金融中心21层2107室</p>
    <p>联系电话：</p>
    <span>版权所有©广东成利建设集团有限公司 &nbsp;&nbsp;&nbsp;&nbsp;粤ICP备18010232号-1</span>

</div>
</div>
</html>

templates/logo.html
{% load staticfiles %}
<input type='hidden' id='loginusername' value='暂无'><input type='hidden' id='loginemail'
                                                          value='暂无'><!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">

    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>企业文化-广东成利建设集团有限公司 </title>
    <link rel="stylesheet" href="{% static 'css/default.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/idangerous_swiper.css' %}">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/SuperSlide.js' %}"></script>
    <script src="{% static 'js/idangerous.swiper.min.js' %}"></script>
    <script src="{% static 'js/idangerous.swiper.progress.js' %}"></script>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="//cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="//cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<div id="index-box">
    <div id="head">
        <img src="{% static 'images/logo.png' %}">
        <div class="head-search">
            <form action="" method="post">
                {% csrf_token %}
                <input type="text" name="keyword">
                <input type="submit" class="submit" value="搜索">
            </form>
        </div>
    </div>
</div>
<!--menu start-->
<div id="menu">
    <div class="menu-top">
        <ul>
            <li>
                <a href={% url 'gdcl:index' %}>首页</a></li>
            <li>
                <a href={% url 'gdcl:description' %}>企业概况</a></li>
            <li class="select">
                <a href={% url 'gdcl:logo' %}>企业文化</a></li>
            <li>
                <a href={% url 'gdcl:rewards' %}>工程业绩</a></li>
            <li>
                <a href={% url 'gdcl:company_news' %}>新闻资讯</a></li>
            <li>
                <a href={% url 'gdcl:contact' %}>加入我们</a></li>
        </ul>
    </div>
    <!--中间部分-->
    <div class="banner-min"
         style="background:url({% static 'images/20170301111230_24232.jpg' %}) no-repeat top center;"></div>
    <div id="banner-middle">
        <div class="qygk-left">
            <div class="qygk-left-top">
                <b></b>
                <h3>企业文化</h3>
            </div>
            <div class="qygk-left-bottom">
                <ul>
                    <li><i class="iconfont newsfont">></i>
                        <a href={% url 'gdcl:logo' %} class="menu-on">品牌标志</a></li>
                    <li><i class="iconfont newsfont">></i>
                        <a href={% url 'gdcl:management' %}>管理理念</a></li>
                    <li><i class="iconfont newsfont">></i>
                        <a href={% url 'gdcl:show' %}>形象展示</a></li>
                    <li><i class="iconfont newsfont">></i>
                        <a href={% url 'gdcl:video' %}>企业视频</a></li>
                    <li><i class="iconfont newsfont">></i>
                        <a href={% url 'gdcl:employee' %} >员工风采</a></li>
                </ul>
            </div>
        </div>
        <div class="qygk-right">
            <div class="munu-info">
                <div id="location">
                    <b></b><span>当前位置 -> <a href={% url 'gdcl:index' %}>首页</a>-><a href={% url 'gdcl:logo' %}>企业文化</a>-><a
                        href={% url 'gdcl:logo' %}>品牌标志</a></span>
                </div>
                <div class="menu-content">
                    <!--内容详情页-->
                    <div class="qywh-top" style="margin-top:30px;">
                        <div id="qywh-top-left" style="float:left;width:50%;text-align:center;line-height:26px;">
                            <p>
                                绿色
                            </p>
                            <p>
                                Green color
                            </p>
                            <p>
                                孕育着生命，
                            </p>
                            <p>
                                Embodies life,
                            </p>
                            <p>
                                孕育着无限希望。
                            </p>
                            <p>
                                Embodies countless hope.
                            </p>
                            <p>
                                昌盛，以蓬勃的生机，
                            </p>
                            <p>
                                Changsheng,with its flourishing vitality,
                            </p>
                            <p>
                                诠释着
                            </p>
                            <p>
                                Interprets
                            </p>
                            <p>
                                她，
                            </p>
                            <p>
                                Its,
                            </p>
                            <p>
                                不变的真谛
                            </p>
                            Uuchanged true meaning
                        </div>
                        <div class="qywh-top-right" style="width:50%;float:left;">
                            <img src="/template/default/img/biaozhi01.jpg" style="margin-top:85px;"/>
                        </div>
                    </div>
                    <div class="qywh-top" style="margin-top:50px;">
                        <div class="qywh-top-right" style="width:50%;float:left;">
                            <img src="/template/default/img/hand.jpg" style="margin-top:15px;margin-left:70px;"/>
                        </div>
                        <div id="qywh-top-left" style="float:left;width:50%;text-align:center;line-height:26px;">
                            <p>
                                看到她，
                            </p>
                            <p>
                                Seeing it
                            </p>
                            <p>
                                你是否想到很多……
                            </p>
                            <p>
                                Reminds you of many,many……
                            </p>
                            <p>
                                绿色－生命，希望
                            </p>
                            <p>
                                Geen－life,hope point;
                            </p>
                            <p>
                                圆满中的突破－破茧后的新生
                            </p>
                            <p>
                                Breakthrough in roundness－rebirth of phoenix;
                            </p>
                            <p>
                                道路－通向远方的地平线
                            </p>
                            <p>
                                Road－horizon towards far away;
                            </p>
                            <p>
                                群体耸立－团结的力量……
                            </p>
                            Upright group－united strength……
                        </div>
                    </div>
                    <div class="qywh-top" style="margin-top:50px;">
                        <div id="qywh-top-left" style="float:left;width:50%;text-align:center;line-height:26px;">
                            <p>
                                那你，一定感受到了，
                            </p>
                            <p>
                                You must feel,
                            </p>
                            <p>
                                勃勃的生机
                            </p>
                            <p>
                                Flourishing vitality,
                            </p>
                            <p>
                                奋发向上的力量
                            </p>
                            <p>
                                Stieeing enterprising force!
                            </p>
                            <p>
                                这，就是昌盛的标志，
                            </p>
                            <p>
                                This，is mark of Changsheng，
                            </p>
                            <p>
                                这就是昌盛！
                            </p>
                            This is Changsheng !
                        </div>
                        <div class="qywh-top-right" style="width:50%;float:left;">
                            <img src="/template/default/img/medal.png"/>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    <script type="text/javascript" src="http://v3.jiathis.com/code/jia.js" charset="utf-8"></script>
    <!--footer-->
<div style="clear:both;"></div>
<div id="footer">
    <div class="foot-top">
        <ul>
            <li><a href={% url 'gdcl:index' %}>首页</a></li>
            <li><a href={% url 'gdcl:description' %}>企业概况</a></li>
            <li><a href={% url 'gdcl:rewards' %}>工程业绩</a></li>
            <li><a href={% url 'gdcl:contact' %}>加入我们</a></li>
        </ul>
    </div>
    <p>地址：珠海市香洲区九州大道中1009号钰海环球金融中心29层2907-08室</p>
    <p>联系电话：</p>
    <span>版权所有©广东成利建设集团有限公司 &nbsp;&nbsp;&nbsp;&nbsp;粤ICP备18010232号-1</span>

</div>
</div>
</html>

templates/project_photo.html
{% load staticfiles %}
<input type='hidden' id='loginusername' value='暂无'><input type='hidden' id='loginemail'
                                                          value='暂无'><!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.01//EN" "http://www.w3.org/TR/html4/strict.dtd">
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8">

    <!-- 上述3个meta标签*必须*放在最前面，任何其他内容都*必须*跟随其后！ -->
    <title>工程业绩-广东成利建设集团有限公司</title>
    <link rel="stylesheet" href="{% static 'css/default.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/style.css' %}"/>
    <link rel="stylesheet" href="{% static 'css/idangerous_swiper.css' %}">
    <script src="{% static 'js/jquery.min.js' %}"></script>
    <script src="{% static 'js/SuperSlide.js' %}"></script>
    <script src="{% static 'js/idangerous.swiper.min.js' %}"></script>
    <script src="{% static 'js/idangerous.swiper.progress.js' %}"></script>
    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!-- WARNING: Respond.js doesn't work if you view the page via file:// -->
    <!--[if lt IE 9]>
      <script src="//cdn.bootcss.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="//cdn.bootcss.com/respond.js/1.4.2/respond.min.js"></script>
    <![endif]-->
</head>
<div id="index-box">
    <div id="head">
        <img src="{% static 'images/logo.png' %}">
        <div class="head-search">
            <form action="" method="post">
                {% csrf_token %}
                <input type="text" name="keyword">
                <input type="submit" class="submit" value="搜索">
            </form>
        </div>
    </div>
</div>
<!--menu start-->
<div id="menu">
    <div class="menu-top">
        <ul>
            <li>
                <a href={% url 'gdcl:index' %}>首页</a></li>
            <li>
                <a href={% url 'gdcl:description' %}>企业概况</a></li>
            <li>
                <a href={% url 'gdcl:logo' %}>企业文化</a></li>
            <li class="select">
                <a href={% url 'gdcl:rewards' %}>工程业绩</a></li>
            <li>
                <a href={% url 'gdcl:company_news' %}>新闻资讯</a></li>
            <li>
                <a href={% url 'gdcl:contact' %}>加入我们</a></li>
        </ul>
    </div>
    <!--中间部分-->
    <div class="banner-min"
         style="background:url({% static 'images/20170301111206_19121.jpg' %}) no-repeat top center;"></div>
    <div id="banner-middle">
        <div class="qygk-left">
            <div class="qygk-left-top">
                <b></b>
                <h3>工程业绩</h3>
            </div>
            <div class="qygk-left-bottom">
                <ul>
                    <li><i class="iconfont newsfont">></i>
                        <a href={% url 'gdcl:rewards' %} >获奖工程</a></li>
                    <li><i class="iconfont newsfont">></i>
                        <a href={% url 'gdcl:project_show' %}>项目展示</a></li>
                    <li><i class="iconfont newsfont">></i>
                        <a href={% url 'gdcl:project_photo' %} class="menu-on">项目实拍</a></li>
                </ul>
            </div>
        </div>
        <div class="qygk-right">
            <div class="munu-info">
                <div id="location">
                    <b></b><span>当前位置 -> <a href={% url 'gdcl:index' %}>首页</a>-><a href={% url 'gdcl:rewards' %}>工程业绩</a>-><a
                        href={% url 'gdcl:project_photo' %}>项目实拍</a></span>
                </div>
                <div class="menu-content">
                    <div class="hjgc">
                        <ul>
                            <li>
                                <a href={% url 'gdcl:yqsz' %}>
                                    <div><img src="{% static 'images/yqsz.png' %}"></div>
                                    <p>银泉山庄</p>
                                </a>
                            </li>
                            <li>
                                <a href={% url 'gdcl:ylgc' %}>
                                    <div><img src="{% static 'images/ylgc.png' %}"></div>
                                    <p>鱼林广场</p>
                                </a>
                            </li>
                            <li>
                                <a href={% url 'gdcl:zhgxhmt' %}>
                                    <div><img src="{% static 'images/zhgxhmt.png' %}"></div>
                                    <p>珠海港鑫和码头</p>
                                </a>
                            </li>
                            <li>
                                <a href={% url 'gdcl:zhsdjzxjxl' %}>
                                    <div><img src="{% static 'images/zhsdjzxjxl.png' %}"></div>
                                    <p>珠海市第九中学教学楼</p>
                                </a>
                            </li>
                            <li>
                                <a href={% url 'gdcl:bthxx' %}>
                                    <div><img src="{% static 'images/bthxx.png' %}"></div>
                                    <p>白藤湖小学</p>
                                </a>
                            </li>
{#                            <li>#}
{#                                <a href="/info_91.html">#}
{#                                    <div><img src="/upload/attached/image/20170427/20170427172119_82221.jpg"></div>#}
{#                                    <p>绅威游艇</p>#}
{#                                </a>#}
{#                            </li>#}
{#                            <li>#}
{#                                <a href="/info_90.html">#}
{#                                    <div><img src="/upload/attached/image/20170427/20170427172029_76681.jpg"></div>#}
{#                                    <p>赛纳宿舍楼</p>#}
{#                                </a>#}
{#                            </li>#}
{#                            <li>#}
{#                                <a href="/info_89.html">#}
{#                                    <div><img src="/upload/attached/image/20170427/20170427171916_78723.jpg"></div>#}
{#                                    <p>赛纳</p>#}
{#                                </a>#}
{#                            </li>#}
{#                            <li>#}
{#                                <a href="/info_88.html">#}
{#                                    <div><img src="/upload/attached/image/20170427/20170427171824_31770.jpg"></div>#}
{#                                    <p>南水汽车客运站</p>#}
{#                                </a>#}
{#                            </li>#}
{#                            <li>#}
{#                                <a href="/info_87.html">#}
{#                                    <div><img src="/upload/attached/image/20170427/20170427171706_25744.jpg"></div>#}
{#                                    <p>锦绣四季花园</p>#}
{#                                </a>#}
{#                            </li>#}
{#                            <li>#}
{#                                <a href="/info_86.html">#}
{#                                    <div><img src="/upload/attached/image/20170427/20170427171516_87512.jpg"></div>#}
{#                                    <p>金海岸文化艺术中心</p>#}
{#                                </a>#}
{#                            </li>#}
{#                            <li>#}
{#                                <a href="/info_85.html">#}
{#                                    <div><img src="/upload/attached/image/20170427/20170427171433_30541.jpg"></div>#}
{#                                    <p>嘉珠时代广场</p>#}
{#                                </a>#}
{#                            </li>#}
                        </ul>
                    </div>
                </div>
            </div>
        </div>
{#        <div class="pages"><a href="index_10_1.html" class="num">上一页</a><span class="current">1</span><a#}
{#                href="index_10_2.html">2</a><a href="index_10_2.html" class="num">下一页</a></div>#}
{#    </div>#}
    <script type="text/javascript" src="http://v3.jiathis.com/code/jia.js" charset="utf-8"></script>
    <!--footer-->
<div style="clear:both;"></div>
<div id="footer">
    <div class="foot-top">
        <ul>
            <li><a href={% url 'gdcl:index' %}>首页</a></li>
            <li><a href={% url 'gdcl:description' %}>企业概况</a></li>
            <li><a href={% url 'gdcl:rewards' %}>工程业绩</a></li>
            <li><a href={% url 'gdcl:contact' %}>加入我们</a></li>
        </ul>
    </div>
    <p>地址：珠海市香洲区九州大道中1009号钰海环球金融中心29层2907-08室</p>
    <p>联系电话：</p>
    <span>版权所有©广东成利建筑集团有限公司 &nbsp;&nbsp;&nbsp;&nbsp;粤ICP备18010232号-1</span>

</div>
</div>
</html>